import { Roboto } from 'next/font/google'
import { Toaster } from "react-hot-toast";



import './globals.css'

import {AppProvider} from "@/components/AppContext";
import Header from "@/components/layout/Header";
import ScrollToTopButton from "@/components/topUpButton/ScrollToTopButton";
import Footer from "@/components/layout/Footer";





const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'SpaceBox Burger',
  description: 'Generated by creating next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="de" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-6xl mx-auto p-4">
          <AppProvider>
            {/* <div id="modal-root"></div> */}
            <Toaster />
            {/*<Rucolaback />*/}
            {/* <Planet /> */}
            <Header />
            {children}
            <ScrollToTopButton />
            <Footer />
            {/* <CookieConsent
              buttonText="Accept"
              enableDeclineButton
              onAccept={() => {
                console.log("Cookies were accepted!");
              }}
              declineButtonText="Decline"
            >
              This website uses cookies to enhance the user experience.
            </CookieConsent> */}
          </AppProvider>
        </main>
      </body>
    </html>
  );
}

