import { Roboto } from 'next/font/google'
import { Toaster } from "react-hot-toast";

import './globals.css'

import {AppProvider} from "@/components/AppContext";
import Header from "@/components/layout/Header";
import ScrollToTopButton from "@/components/topUpButton/ScrollToTopButton";
import Footer from "@/components/layout/Footer";





const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Space Burger',
  description: 'Generated by creating next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      <body className={roboto.className}>
        <main className="max-w-6xl mx-auto p-4">
          <AppProvider>
            <Toaster/>
            {/*<Rucolaback />*/}
            {/* <Planet /> */}
            <Header />
            {children}
            <ScrollToTopButton />
            <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
